version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../Dataset:/Dataset
      - ../pyscript:/app
      - ../env:/app/env
      - ../init:/init
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=HARPA
      - POSTGRES_LOG_MIN_MESSAGES=notice
      - POSTGRES_LOG_STATEMENT=all
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_LISTEN_PORT=80
    restart: unless-stopped
    networks:
      - internal

  python-app:
    image: python:3.9
    depends_on:
      - db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../pyscript:/app
      - ../env:/app/env
      - ../Dataset:/Dataset
      - ../init:/init
      - ../machine_learning:/machine_learning
    working_dir: /app
    command: /bin/bash -c "pip install --no-cache-dir -r requirements.txt && python main.py"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=HARPA
    networks:
      - internal

  predictions:
    image: python:3.9
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../pyscript:/app
      - ../env:/app/env
      - ../Dataset:/Dataset
      - ../init:/init
      - ../machine_learning:/machine_learning
    working_dir: /app
    command: /bin/bash -c "pip install --no-cache-dir -r requirements.txt && python predict_future_consumption.py"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=HARPA
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
