version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - ./../init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
      - ./../Dataset:/csv
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=HARPA

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_LISTEN_PORT=80
    restart: unless-stopped

  python-app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=HARPA

volumes:
  postgres_data:
